export const FETCH_ALL_CATEGORIES_SUCCEEDED = 'FETCH_ALL_CATEGORIES_SUCCEEDED';
export const FETCH_ALL_PRODUCTS_SUCCEEDED = 'FETCH_ALL_PRODUCTS_SUCCEEDED';
export const CATEGORY_CLICKED = 'CATEGORY_CLICKED';