export const FETCH_ALL_CATEGORIES_SUCCEEDED = 'FETCH_ALL_CATEGORIES_SUCCEEDED';
export const FETCH_ALL_PRODUCTS_SUCCEEDED = 'FETCH_ALL_PRODUCTS_SUCCEEDED';
export const SET_FILTER = 'SET_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';